# Generated by Django 3.2.9 on 2022-09-21 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConstants',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('site_name', models.CharField(blank=True, default='Devme', max_length=100, null=True)),
                ('site_email', models.CharField(blank=True, default='devme@gmail.com', max_length=100, null=True)),
                ('site_email2', models.CharField(blank=True, default='kibebekevin@gmail.com', max_length=100, null=True)),
                ('theme_color', models.CharField(blank=True, default='#EF3724', max_length=100, null=True)),
                ('site_url', models.URLField(blank=True, default='https://illuminate.com', null=True)),
                ('cv_file', models.FileField(blank=True, default='docs/kevin_kibebe_cv.pdf', null=True, upload_to='docs/')),
                ('description', models.TextField(blank=True, default='sample site description', null=True)),
                ('key_words', models.TextField(blank=True, default='illuminate', null=True)),
                ('address', models.CharField(blank=True, default='Moi University,Kesses, Eldoret Uasin Gishu County Kenya', max_length=250, null=True)),
                ('location', models.CharField(blank=True, default='Eldoret,Kenya ', max_length=250, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+254798449624', max_length=128, null=True, region=None, verbose_name='phone')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+254796268817', max_length=128, null=True, region=None, verbose_name='phone2')),
                ('working_days', models.CharField(blank=True, default='mon-fri', max_length=250, null=True)),
                ('site_content', models.CharField(blank=True, max_length=250, null=True)),
                ('working_hours', models.CharField(blank=True, default='8am-10pm', max_length=250, null=True)),
                ('closed_days', models.CharField(blank=True, default='sun', max_length=250, null=True)),
                ('special_days', models.CharField(blank=True, default='sat & holidays', max_length=250, null=True)),
                ('special_hours', models.CharField(blank=True, default='sat & holidays', max_length=250, null=True)),
                ('facebook', models.URLField(blank=True, default='https://web.facebook.com/kevy.kibbz/', max_length=250, null=True)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/Kevin36285655', max_length=250, null=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/kevviey/', max_length=250, null=True)),
                ('whatsapp', models.URLField(blank=True, default='https://wa.link/r9fxm4', max_length=250, null=True)),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com/in/chill-cash-260aba206/', max_length=250, null=True)),
                ('youtube', models.URLField(blank=True, default='https://youtube.com', max_length=250, null=True)),
                ('favicon', models.ImageField(blank=True, default='logos/favicon.ico', null=True, upload_to='logos/')),
                ('icon_180', models.ImageField(blank=True, default='favicon-180x180.png', null=True, upload_to='logos/')),
                ('icon_32', models.ImageField(blank=True, default='favicon-32x32.png', null=True, upload_to='logos/')),
                ('icon_16', models.ImageField(blank=True, default='favicon-16x16.png', null=True, upload_to='logos/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'site_constants',
                'db_table': 'site_constants',
            },
        ),
    ]
