# Generated by Django 3.2.9 on 2022-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconstants',
            name='client_satisfactory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siteconstants',
            name='clients',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siteconstants',
            name='completed_projects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siteconstants',
            name='ongoing_projects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
