# Generated by Django 3.2.9 on 2022-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
