# Generated by Django 3.2.9 on 2022-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220921_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='caption'),
        ),
    ]
